// // import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header";
// import Providers from "./providers";

// // const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Home Page",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Providers>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }
